#' print.ssize
#'
#' Print objects of class 'ssize' generated by \code{\link{survey_size}}.
#'
#' @param x Class 'ssize' object to print
#'
#' @param ... Further arguments passed to or from other methods.
#'
#' @return None
#'
#' @export
#'
#' @examples
#' \dontrun{
#' library(surveytools)
#' foo <- survey_size(population_size = 400)
#' print(foo)
#' }

print.ssize <- function(x, ...) {
    cat('SURVEY SIZE CALCULATION\n\n',
              'Population size (N):', x$population_size, '\n',
              'Required sample size (n):', x$required_sample, '\n\n',
        'Assumptions:\n',
        'i) error margin =', x$error_margin, '\n',
        'ii) confidence level =', x$confidence_level, '\n',
        'iii) response distribution =', x$response_distribution)
}
